- README.md
- examples/pom.xml
* addressing the checklist items
> readme doc updated to be in par with checklist

- sdk/src/main/java/com/microsoft/azure/cosmosdb/rx/internal/RxDocumentClientImpl.java
As requested by @moderakh here is a PR to resolve #24
> increasing max http header size from 8192 to 32768

- sdk/src/main/java/com/microsoft/azure/cosmosdb/internal/BaseAuthorizationTokenProvider.java
- sdk/src/main/java/com/microsoft/azure/cosmosdb/internal/routing/InMemoryCollectionRoutingMap.java
- sdk/src/main/java/com/microsoft/azure/cosmosdb/rx/internal/RxDocumentClientImpl.java
- sdk/src/test/java/com/microsoft/azure/cosmosdb/internal/routing/InMemoryCollectionRoutingMapTest.java
- sdk/src/test/java/com/microsoft/azure/cosmosdb/internal/routing/RoutingMapProviderHelperTest.java
- sdk/src/test/java/com/microsoft/azure/cosmosdb/rx/CollectionQueryTest.java
- sdk/src/test/java/com/microsoft/azure/cosmosdb/rx/OfferReadReplaceTest.java
- sdk/src/test/java/com/microsoft/azure/cosmosdb/rx/UserQueryTest.java
This PR has small features to improve performance in some operations.
> Performance

- README.md
Signed-off-by: Bruno Borges <bruno.borges@microsoft.com>
> Update README with proper Maven badge

- benchmark/pom.xml
- commons-test-utils/pom.xml
- commons/pom.xml
- commons/src/main/java/com/microsoft/azure/cosmosdb/internal/HttpConstants.java
- direct-impl/pom.xml
- examples/pom.xml
- gateway/pom.xml
- pom.xml
- sdk/pom.xml
> bumped version to 2.4.5 for V2 SDK release

- benchmark/pom.xml
- commons-test-utils/pom.xml
- commons/pom.xml
- commons/src/main/java/com/microsoft/azure/cosmosdb/PartitionKeyDefinition.java
- commons/src/main/java/com/microsoft/azure/cosmosdb/PartitionKeyDefinitionVersion.java
- commons/src/main/java/com/microsoft/azure/cosmosdb/internal/HttpConstants.java
- direct-impl/pom.xml
- direct-impl/src/test/java/com/microsoft/azure/cosmosdb/PartitionKeyHashingTests.java
- examples/pom.xml
- gateway/pom.xml
- pom.xml
- sdk/pom.xml
bumped version to 3.0.0-beta-3
> hashv2 support for V3 sdk 

- CODEOWNERS
> Add christopheranderson and kushagraThapar to CODEOWNERS

- CODEOWNERS
> Add christopheranderson and kushagraThapar to CODEOWNERS (v3)

- commons-test-utils/src/main/java/com/microsoft/azure/cosmosdb/rx/ResourceResponseValidator.java
- commons/src/main/java/com/microsoft/azure/cosmosdb/Resource.java
- commons/src/test/java/com/microsoft/azure/cosmosdb/DocumentTests.java
- sdk/src/test/java/com/microsoft/azure/cosmosdb/rx/DocumentCrudTest.java
- sdk/src/test/java/com/microsoft/azure/cosmosdb/rx/internal/ConsistencyTestsBase.java
fixes #154 
- Switches all `java.util.Date` references to `java.time.OffsetDateTime`
> use OffsetDateTime - fixes #154

- commons/src/main/java/com/azure/data/cosmos/CosmosItemProperties.java
- commons/src/main/java/com/azure/data/cosmos/CosmosStoredProcedureSettings.java
- commons/src/main/java/com/azure/data/cosmos/CosmosTriggerSettings.java
- commons/src/main/java/com/azure/data/cosmos/CosmosUserDefinedFunctionSettings.java
- commons/src/main/java/com/azure/data/cosmos/Database.java
- commons/src/main/java/com/azure/data/cosmos/Document.java
- commons/src/main/java/com/azure/data/cosmos/DocumentCollection.java
- commons/src/main/java/com/azure/data/cosmos/PartitionKeyRange.java
- commons/src/main/java/com/azure/data/cosmos/Permission.java
- commons/src/main/java/com/azure/data/cosmos/Resource.java
- commons/src/main/java/com/azure/data/cosmos/StoredProcedure.java
- sdk/src/main/java/com/azure/data/cosmos/CosmosConflict.java
- sdk/src/main/java/com/azure/data/cosmos/CosmosConflictProperties.java
- sdk/src/main/java/com/azure/data/cosmos/CosmosConflictRequestOptions.java
- sdk/src/main/java/com/azure/data/cosmos/CosmosConflictResponse.java
- sdk/src/main/java/com/azure/data/cosmos/CosmosContainer.java
- sdk/src/main/java/com/azure/data/cosmos/CosmosPermissionResponse.java
- sdk/src/main/java/com/azure/data/cosmos/CosmosPermissionSettings.java
- sdk/src/main/java/com/azure/data/cosmos/CosmosUser.java
- sdk/src/main/java/com/azure/data/cosmos/CosmosUserSettings.java
- sdk/src/test/java/com/azure/data/cosmos/CosmosResponseValidator.java
- sdk/src/test/java/com/azure/data/cosmos/rx/CosmosConflictTest.java
- sdk/src/test/java/com/azure/data/cosmos/rx/PermissionCrudTest.java
Fixing Permission tests
Making id method of Resource package private and adding id on
individual resource classes to enable fluent composition
> Adding conflict api

- examples/src/main/java/com/azure/data/cosmos/examples/ChangeFeed/SampleChangeFeedProcessor.java
- sdk/src/main/java/com/azure/data/cosmos/ChangeFeedProcessor.java
- sdk/src/main/java/com/azure/data/cosmos/ChangeFeedProcessorOptions.java
- sdk/src/main/java/com/azure/data/cosmos/internal/changefeed/implementation/ChangeFeedProcessorBuilderImpl.java
- sdk/src/main/java/com/azure/data/cosmos/internal/changefeed/implementation/EqualPartitionsBalancingStrategy.java
- sdk/src/test/java/com/azure/data/cosmos/rx/ChangeFeedProcessorTest.java
Most of these changes are based on the API review feedback captured in the Excel spreadsheet.
> CFP: Refactoring and removing "partition" settings from the options

- sdk/src/main/java/com/azure/data/cosmos/BridgeInternal.java
- sdk/src/main/java/com/azure/data/cosmos/ClientSideRequestStatistics.java
- sdk/src/main/java/com/azure/data/cosmos/CosmosClientException.java
- sdk/src/main/java/com/azure/data/cosmos/CosmosResponse.java
- sdk/src/main/java/com/azure/data/cosmos/CosmosResponseDiagnosticStatistics.java
- sdk/src/main/java/com/azure/data/cosmos/CosmosResponseDiagnostics.java
- sdk/src/main/java/com/azure/data/cosmos/FeedResponse.java
- sdk/src/main/java/com/azure/data/cosmos/FeedResponseDiagnostics.java
- sdk/src/main/java/com/azure/data/cosmos/internal/ClientRetryPolicy.java
- sdk/src/main/java/com/azure/data/cosmos/internal/DocumentServiceRequestContext.java
- sdk/src/main/java/com/azure/data/cosmos/internal/ResourceResponse.java
- sdk/src/main/java/com/azure/data/cosmos/internal/RxDocumentServiceResponse.java
- sdk/src/main/java/com/azure/data/cosmos/internal/StoredProcedureResponse.java
- sdk/src/main/java/com/azure/data/cosmos/internal/directconnectivity/ConsistencyReader.java
- sdk/src/main/java/com/azure/data/cosmos/internal/directconnectivity/ConsistencyWriter.java
- sdk/src/main/java/com/azure/data/cosmos/internal/directconnectivity/GatewayAddressCache.java
- sdk/src/main/java/com/azure/data/cosmos/internal/directconnectivity/ReplicatedResourceClient.java
- sdk/src/main/java/com/azure/data/cosmos/internal/directconnectivity/StoreClient.java
- sdk/src/main/java/com/azure/data/cosmos/internal/directconnectivity/StoreReader.java
- sdk/src/main/java/com/azure/data/cosmos/internal/directconnectivity/StoreResponse.java
- sdk/src/main/java/com/azure/data/cosmos/internal/query/AggregateDocumentQueryExecutionContext.java
- sdk/src/main/java/com/azure/data/cosmos/internal/query/OrderByDocumentQueryExecutionContext.java
- sdk/src/main/java/com/azure/data/cosmos/internal/query/OrderByUtils.java
- sdk/src/main/java/com/azure/data/cosmos/internal/query/ParallelDocumentQueryExecutionContext.java
- sdk/src/main/java/com/azure/data/cosmos/internal/query/TopDocumentQueryExecutionContext.java
- sdk/src/test/java/com/azure/data/cosmos/internal/FeedResponseListValidator.java
- sdk/src/test/java/com/azure/data/cosmos/rx/CollectionCrudTest.java
- sdk/src/test/java/com/azure/data/cosmos/rx/ParallelDocumentQueryTest.java
Wrapped Client Side Request Statistics in Cosmos Response Diagnostics. 
Exposed only toString() and requestLatency()
> Wrapped Client Side Request Statistics

- README.md
- changelog/README.md
- dev.md
- examples/src/main/java/com/azure/data/cosmos/examples/HelloWorldDemo.java
- Updates Readme for 3.0.0
- Adds dev.md for dev doc info
- Adds a HelloWorldExample for the content on the readme
- Updates changelog
> Readme updates

- sdk/src/main/java/com/azure/data/cosmos/CosmosDatabase.java
Renaming docs where collection is used instead of container
Renaming the param containerSettings to containerProperties
> Fixing potential NPEs

- gateway/src/main/java/com/microsoft/azure/cosmosdb/rx/internal/query/PipelinedDocumentQueryExecutionContext.java
- gateway/src/main/java/com/microsoft/azure/cosmosdb/rx/internal/query/TopDocumentQueryExecutionContext.java
Fix for an issue where offset limit queries might not return expected number of results.
> offset-limit query fix

- README.md
- benchmark/pom.xml
- commons-test-utils/pom.xml
- commons/pom.xml
- commons/src/main/java/com/microsoft/azure/cosmosdb/internal/HttpConstants.java
- direct-impl/pom.xml
- examples/pom.xml
- gateway/pom.xml
- pom.xml
- sdk/pom.xml
Updated versions to 2.6.3 for release
> Updated release version to 2.6.3

- direct-impl/src/main/java/com/microsoft/azure/cosmosdb/internal/directconnectivity/ConsistencyWriter.java
- direct-impl/src/test/java/com/microsoft/azure/cosmosdb/internal/directconnectivity/AddressResolverTest.java
- sdk/src/test/java/com/microsoft/azure/cosmosdb/rx/OfferReadReplaceTest.java
- sdk/src/test/java/com/microsoft/azure/cosmosdb/rx/TestSuiteBase.java
- sdk/src/test/java/com/microsoft/azure/cosmosdb/rx/UserCrudTest.java
Fixes a potential NPE bug which is discovered and fixed in v3
Fixes some tests
> Potential NPE bug fix

- sdk/src/test/java/com/microsoft/azure/cosmosdb/rx/CollectionCrudTest.java
* Fixed breaking emulator changes (port from this PR: https://github.com/Azure/azure-sdk-for-java/pull/6352)
* Added test to replace collection after setting time to live property on an existing collection.
> Added replace collection with time to live property test

- README.md
- benchmark/pom.xml
- commons-test-utils/pom.xml
- commons/pom.xml
- commons/src/main/java/com/microsoft/azure/cosmosdb/internal/HttpConstants.java
- direct-impl/pom.xml
- examples/pom.xml
- gateway/pom.xml
- pom.xml
- sdk/pom.xml
Bump versions to 2.6.4 for release
> Bump versions to 2.6.4 for release

- benchmark/pom.xml
- changelog/README.md
- commons-test-utils/pom.xml
- commons/pom.xml
- commons/src/main/java/com/microsoft/azure/cosmosdb/internal/HttpConstants.java
- direct-impl/pom.xml
- examples/pom.xml
- gateway/pom.xml
- pom.xml
- sdk/pom.xml
* Updated version to next snapshot version: 2.6.5-SNAPSHOT
* Updated changelog to reflect new changes.
> Updated version to next snapshot version and updated changelog

- benchmark/pom.xml
- commons-test-utils/pom.xml
- commons/pom.xml
- commons/src/main/java/com/microsoft/azure/cosmosdb/internal/HttpConstants.java
- direct-impl/pom.xml
- examples/pom.xml
- gateway/pom.xml
- pom.xml
- sdk/pom.xml
> Bumping version from 2.6.5-SNAPSHOT to 2.6.5

- README.md
- benchmark/pom.xml
- changelog/README.md
- commons-test-utils/pom.xml
- commons/pom.xml
- commons/src/main/java/com/microsoft/azure/cosmosdb/internal/HttpConstants.java
- direct-impl/pom.xml
- examples/pom.xml
- gateway/pom.xml
- pom.xml
- sdk/pom.xml
Updating Readme and changelog for 2.6.5 release
> Bumping version to 2.6.6-SNAPSHOT

- benchmark/pom.xml
- commons-test-utils/pom.xml
- commons/pom.xml
- commons/src/main/java/com/microsoft/azure/cosmosdb/internal/HttpConstants.java
- direct-impl/pom.xml
- examples/pom.xml
- gateway/pom.xml
- pom.xml
- sdk/pom.xml
* Updated version to 2.6.7 for release
> Updated versions to 2.6.7 for release

- README.md
- benchmark/pom.xml
- changelog/README.md
- commons-test-utils/pom.xml
- commons/pom.xml
- commons/src/main/java/com/microsoft/azure/cosmosdb/internal/HttpConstants.java
- direct-impl/pom.xml
- examples/pom.xml
- gateway/pom.xml
- pom.xml
- sdk/pom.xml
* Post release version update 2.6.8-SNAPSHOT
* Updated changelog and readme
> Post release version update to 2.6.8-SNAPSHOT. 

- benchmark/pom.xml
- commons-test-utils/pom.xml
- commons/pom.xml
- commons/src/main/java/com/microsoft/azure/cosmosdb/internal/HttpConstants.java
- direct-impl/pom.xml
- examples/pom.xml
- gateway/pom.xml
- pom.xml
- sdk/pom.xml
Updating the version to 2.6.8 from 2.6.8.snapshot for release
> Updating the version to 2.6.8 for release

- README.md
- changelog/README.md
Updating changelog and readme to reflect the new release 2.6.8
> Updating changelog and readme

- pom.xml
Updated netty versions to 4.1.50.Final
> Updated netty versions to 4.1.50.Final

- gateway/src/main/java/com/microsoft/azure/cosmosdb/rx/internal/query/OrderByDocumentQueryExecutionContext.java
- sdk/src/test/java/com/microsoft/azure/cosmosdb/rx/QueryValidationTests.java
* This PR is a duplicate of PR : https://github.com/Azure/azure-cosmosdb-java/pull/339
* Since that PR is experiencing some issues with running CI because of permissions.
> Fix adobe duplicate result using continuation token

- benchmark/pom.xml
- commons-test-utils/pom.xml
- commons/pom.xml
- commons/src/main/java/com/microsoft/azure/cosmosdb/internal/HttpConstants.java
- direct-impl/pom.xml
- examples/pom.xml
- gateway/pom.xml
- pom.xml
- sdk/pom.xml
> Updating version to 2.6.10

- README.md
- benchmark/pom.xml
- changelog/README.md
- commons-test-utils/pom.xml
- commons/pom.xml
- commons/src/main/java/com/microsoft/azure/cosmosdb/internal/HttpConstants.java
- direct-impl/pom.xml
- examples/pom.xml
- gateway/pom.xml
- pom.xml
- sdk/pom.xml
Updating version to 2.6.11-SNAPSHOT and updating Readme and change log
> Updating version to 2.6.11-SNAPSHOT and updating Readme and change log

- benchmark/pom.xml
- commons-test-utils/pom.xml
- commons/pom.xml
- commons/src/main/java/com/microsoft/azure/cosmosdb/internal/HttpConstants.java
- direct-impl/pom.xml
- examples/pom.xml
- gateway/pom.xml
- pom.xml
- sdk/pom.xml
Version bump 2.6.11 for PR https://github.com/Azure/azure-cosmosdb-java/pull/360
> Version bump 2.6.11

- README.md
- benchmark/pom.xml
- changelog/README.md
- commons-test-utils/pom.xml
- commons/pom.xml
- commons/src/main/java/com/microsoft/azure/cosmosdb/internal/HttpConstants.java
- direct-impl/pom.xml
- examples/pom.xml
- gateway/pom.xml
- pom.xml
- sdk/pom.xml
* Updated versions for release to 2.6.12
> Updated versions for release to 2.6.12

- direct-impl/src/main/java/com/microsoft/azure/cosmosdb/internal/directconnectivity/rntbd/RntbdClientChannelHandler.java
* DUPLICATE of this PR - https://github.com/Azure/azure-cosmosdb-java/pull/372
* Testing CIs
> DUPLICATE - port openssl fix from v4 to v2

- gateway/src/main/java/com/microsoft/azure/cosmosdb/rx/internal/RxGatewayStoreModel.java
- sdk/src/main/java/com/microsoft/azure/cosmosdb/rx/internal/RxDocumentClientImpl.java
* Fixed issue by not passing session token to query plan request
* Reference code : https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/GatewayStoreModel.cs#L196
> Fixed issue by not passing session token to query plan request

- README.md
- benchmark/pom.xml
- changelog/README.md
- commons-test-utils/pom.xml
- commons/pom.xml
- commons/src/main/java/com/microsoft/azure/cosmosdb/internal/HttpConstants.java
- direct-impl/pom.xml
- examples/pom.xml
- gateway/pom.xml
- pom.xml
- sdk/pom.xml
Replica of https://github.com/Azure/azure-cosmosdb-java/pull/390 as Annie having permission issue
> Releasing 2.6.14

- README.md
- benchmark/pom.xml
- changelog/README.md
- commons-test-utils/pom.xml
- commons/pom.xml
- commons/src/main/java/com/microsoft/azure/cosmosdb/internal/HttpConstants.java
- direct-impl/pom.xml
- examples/pom.xml
- gateway/pom.xml
- pom.xml
- sdk/pom.xml
> Version bump to 2.6.15

- direct-impl/src/main/java/com/microsoft/azure/cosmosdb/internal/directconnectivity/RntbdTransportClient.java
- direct-impl/src/main/java/com/microsoft/azure/cosmosdb/internal/directconnectivity/rntbd/RntbdClientChannelPool.java
Mirror of https://github.com/Azure/azure-cosmosdb-java/pull/395
> Mirror of https://github.com/Azure/azure-cosmosdb-java/pull/395

- README.md
- benchmark/pom.xml
- changelog/README.md
- commons-test-utils/pom.xml
- commons/pom.xml
- commons/src/main/java/com/microsoft/azure/cosmosdb/internal/HttpConstants.java
- direct-impl/pom.xml
- examples/pom.xml
- gateway/pom.xml
- pom.xml
- sdk/pom.xml
> Version Bump to 2.6.16
