sdk/src/main/java/com/microsoft/azure/cosmosdb/rx/internal/RxDocumentClientImpl.java
sdk/src/test/java/com/microsoft/azure/cosmosdb/rx/DocumentCrudTest.java

Set the default maxChunkSize for HttpObjectAggregationConfigurator to 2 MB as CosmosDB allows documents of size upto 2 MB
Fixes #33

Increase response chunk size limit to 2 MB

---

sdk/src/main/java/com/microsoft/azure/cosmosdb/rx/internal/caches/RxCollectionCache.java

Fix minor javadoc error preventing javadocs from being successfully generated (even though it is internal API)

Fix minor javadoc error

---

sdk/src/main/java/com/microsoft/azure/cosmosdb/JsonSerializable.java
sdk/src/main/java/com/microsoft/azure/cosmosdb/PermissionMode.java
sdk/src/main/java/com/microsoft/azure/cosmosdb/SqlParameter.java
sdk/src/main/java/com/microsoft/azure/cosmosdb/TriggerOperation.java
sdk/src/main/java/com/microsoft/azure/cosmosdb/TriggerType.java
sdk/src/main/java/com/microsoft/azure/cosmosdb/internal/EndpointManager.java
sdk/src/main/java/com/microsoft/azure/cosmosdb/internal/query/ItemType.java
sdk/src/main/java/com/microsoft/azure/cosmosdb/internal/routing/PartitionKeyComponentType.java
sdk/src/main/java/com/microsoft/azure/cosmosdb/rx/internal/DatabaseAccountManagerInternal.java
sdk/src/main/java/com/microsoft/azure/cosmosdb/rx/internal/ICollectionRoutingMapCache.java
sdk/src/main/java/com/microsoft/azure/cosmosdb/rx/internal/IDocumentClientRetryPolicy.java
sdk/src/main/java/com/microsoft/azure/cosmosdb/rx/internal/IRetryPolicy.java
sdk/src/main/java/com/microsoft/azure/cosmosdb/rx/internal/IRetryPolicyFactory.java
sdk/src/test/java/com/microsoft/azure/cosmosdb/internal/routing/InMemoryCollectionRoutingMapTest.java
sdk/src/test/java/com/microsoft/azure/cosmosdb/rx/AttachmentCrudTest.java
sdk/src/test/java/com/microsoft/azure/cosmosdb/rx/PermissionCrudTest.java
sdk/src/test/java/com/microsoft/azure/cosmosdb/rx/PermissionQueryTest.java
sdk/src/test/java/com/microsoft/azure/cosmosdb/rx/StoredProcedureCrudTest.java
sdk/src/test/java/com/microsoft/azure/cosmosdb/rx/StoredProcedureUpsertReplaceTest.java
sdk/src/test/java/com/microsoft/azure/cosmosdb/rx/TriggerCrudTest.java
sdk/src/test/java/com/microsoft/azure/cosmosdb/rx/TriggerUpsertReplaceTest.java

This PR just remove redundant sentence such as 
¨T extends Object¨ once all objects extend Java that is unnecessary and also a public method in the interface that is defined in the JVM spec.
https://docs.oracle.com/javase/specs/jls/se7/html/jls-9.html#jls-9.4

Remove redundant sentences

---

sdk/pom.xml

Building the SDK under JDK 11 fails due to the outdated version of maven-javadoc-plugin specified in the Maven pom file. Version 2.9.1 was released in June 2013, and is not supported under JDK 11. I have changed this to instead use 3.0.1, which was released in May 2018. SDK compilation now succeeds under JDK 11 (as well as earlier JDK releases).

Upgrade to newer release of the maven-javadoc-plugin

---

CODEOWNERS

Fixed syntax as per
https://help.github.com/en/articles/about-code-owners#codeowners-syntax

Fixed CODEOWNERs syntax

---

examples/src/main/java/com/microsoft/azure/cosmos/examples/BasicDemo.java
sdk/src/main/java/com/microsoft/azure/cosmos/CosmosClient.java
sdk/src/main/java/com/microsoft/azure/cosmos/CosmosContainer.java
sdk/src/main/java/com/microsoft/azure/cosmos/CosmosItem.java
sdk/src/main/java/com/microsoft/azure/cosmos/CosmosItemRequestOptions.java
sdk/src/main/java/com/microsoft/azure/cosmos/CosmosItemResponse.java
sdk/src/main/java/com/microsoft/azure/cosmos/CosmosItemSettings.java
sdk/src/test/java/com/microsoft/azure/cosmos/CosmosItemCrudTest.java
sdk/src/test/java/com/microsoft/azure/cosmos/CosmosResponseValidator.java

Cosmos Item now has a CosmosItem client and CosmosItemSetting resource objects. 
container.getItem() now takes id and partitionkey
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/azure-cosmosdb-java/120)

V3 cosmositem refactoring

---

.gitignore
README.md
benchmark/pom.xml
commons-test-utils/pom.xml
commons/pom.xml
commons/src/main/java/com/microsoft/azure/cosmosdb/internal/HttpConstants.java
direct-impl/pom.xml
examples/pom.xml
gateway/pom.xml
pom.xml
sdk/pom.xml

This PR:
- closes #168 - renames the packages to azure-cosmos-* (from azure-cosmosdb-*)
- bumps the version to 3.0.0-a1 (which I released adhoc) and then 3.0.0-a1-SNAPSHOT
- adds antrun:run@default-cli goal to collect the packages into an easy format for publishing (and updates README)
Recommend disabling seeing whitespace changes in the PR for the Readme. My markdown prettifier cleaned up some whitespace stuff.

artifact renaming, versioning update, and jar collection command

---

benchmark/pom.xml
commons-test-utils/pom.xml
commons/src/main/java/com/microsoft/azure/cosmosdb/rx/internal/Configs.java
commons/src/test/java/com/microsoft/azure/cosmosdb/rx/internal/ConfigsTests.java
examples/pom.xml
examples/src/test/java/com/microsoft/azure/cosmosdb/rx/examples/CollectionCRUDAsyncAPITest.java
examples/src/test/java/com/microsoft/azure/cosmosdb/rx/examples/ConflictAPITest.java
examples/src/test/java/com/microsoft/azure/cosmosdb/rx/examples/DatabaseCRUDAsyncAPITest.java
examples/src/test/java/com/microsoft/azure/cosmosdb/rx/examples/DocumentCRUDAsyncAPITest.java
examples/src/test/java/com/microsoft/azure/cosmosdb/rx/examples/DocumentQueryAsyncAPITest.java
examples/src/test/java/com/microsoft/azure/cosmosdb/rx/examples/InMemoryGroupbyTest.java
examples/src/test/java/com/microsoft/azure/cosmosdb/rx/examples/OfferCRUDAsyncAPITest.java
examples/src/test/java/com/microsoft/azure/cosmosdb/rx/examples/StoredProcedureAsyncAPITest.java
examples/src/test/java/com/microsoft/azure/cosmosdb/rx/examples/TestBase.java
examples/src/test/java/com/microsoft/azure/cosmosdb/rx/examples/TokenResolverTest.java
examples/src/test/java/com/microsoft/azure/cosmosdb/rx/examples/UniqueIndexAsyncAPITest.java
gateway/pom.xml
pom.xml
sdk/src/test/java/com/microsoft/azure/cosmosdb/rx/DocumentClientResourceLeakTest.java
sdk/src/test/java/com/microsoft/azure/cosmosdb/rx/TestSuiteBase.java
sdk/src/test/java/com/microsoft/azure/cosmosdb/rx/internal/SpyClientUnderTestFactory.java

**TODO:**
`DirectHttpsClientUnderTest` now ensures that the HTTPS protocol is used.
Confirmed: no test failures that are the result of assuming the default protocol is HTTPS.
**Also found and fixed:** A dependency issue introduced by our use of `mockito` and `hamcrest` as illustrated here:
```
com.microsoft.azure:azure-cosmosdb-examples:jar:2.4.5
+- org.mockito:mockito-core:jar:1.10.19:test
|  \- org.hamcrest:hamcrest-core:jar:1.1:test
\- org.hamcrest:hamcrest-all:jar:1.3:test
```
See the pom.xml changes and run this command to verify the fix.
```
mvn dependency:tree -Dverbose -Dincludes=org.hamcrest
```
This issue has also been addressed for v3 on this branch: `danoble/rntbd/v3` and `danoble/rntbd/repeat-v3`

Resolved: TCP is now the default direct mode protocol #166.

---

sdk/src/main/java/com/azure/data/cosmos/internal/changefeed/implementation/LeaseStoreManagerImpl.java
sdk/src/main/java/com/azure/data/cosmos/internal/changefeed/implementation/PartitionSupervisorImpl.java

Fix issue with the restarting of the processor; the executor cannot be shutdown since this will stop any future execution using it.

CFP: fix issue with restarting an existing processor

---

gateway/src/main/java/com/microsoft/azure/cosmosdb/rx/internal/ClientRetryPolicy.java
gateway/src/main/java/com/microsoft/azure/cosmosdb/rx/internal/query/DocumentProducer.java
gateway/src/main/java/com/microsoft/azure/cosmosdb/rx/internal/query/QueryPlanRetriever.java

to ensure for in fly requests we retry on the other regions `ClientRetryPolicy#onBeforeRequest` should be invoked.
This was missing in QueryPlanRetrieval and DocumentProducer.

bugfix: try other regions on multimaster for query when the current region is unavailable

---

commons/src/main/java/com/microsoft/azure/cosmosdb/BridgeInternal.java
commons/src/main/java/com/microsoft/azure/cosmosdb/DocumentClientException.java
commons/src/main/java/com/microsoft/azure/cosmosdb/internal/ByteBufferPool.java
commons/src/main/java/com/microsoft/azure/cosmosdb/internal/directconnectivity/AddressInformation.java
commons/src/main/java/com/microsoft/azure/cosmosdb/internal/directconnectivity/HttpUtils.java
commons/src/main/java/com/microsoft/azure/cosmosdb/internal/directconnectivity/StoreResult.java
commons/src/main/java/com/microsoft/azure/cosmosdb/internal/directconnectivity/Uri.java
direct-impl/src/main/java/com/microsoft/azure/cosmosdb/internal/directconnectivity/AddressSelector.java
direct-impl/src/main/java/com/microsoft/azure/cosmosdb/internal/directconnectivity/ConsistencyWriter.java
direct-impl/src/main/java/com/microsoft/azure/cosmosdb/internal/directconnectivity/ErrorUtils.java
direct-impl/src/main/java/com/microsoft/azure/cosmosdb/internal/directconnectivity/HttpClientUtils.java
direct-impl/src/main/java/com/microsoft/azure/cosmosdb/internal/directconnectivity/HttpTransportClient.java
direct-impl/src/main/java/com/microsoft/azure/cosmosdb/internal/directconnectivity/ResponseUtils.java
direct-impl/src/main/java/com/microsoft/azure/cosmosdb/internal/directconnectivity/RntbdTransportClient.java
direct-impl/src/main/java/com/microsoft/azure/cosmosdb/internal/directconnectivity/StoreReader.java
direct-impl/src/test/java/com/microsoft/azure/cosmosdb/internal/directconnectivity/AddressSelectorTest.java
direct-impl/src/test/java/com/microsoft/azure/cosmosdb/internal/directconnectivity/AddressSelectorWrapper.java
direct-impl/src/test/java/com/microsoft/azure/cosmosdb/internal/directconnectivity/ConsistencyReaderTest.java
direct-impl/src/test/java/com/microsoft/azure/cosmosdb/internal/directconnectivity/ConsistencyWriterTest.java
direct-impl/src/test/java/com/microsoft/azure/cosmosdb/internal/directconnectivity/EndpointMock.java
direct-impl/src/test/java/com/microsoft/azure/cosmosdb/internal/directconnectivity/HttpTransportClientTest.java
direct-impl/src/test/java/com/microsoft/azure/cosmosdb/internal/directconnectivity/QuorumReaderTest.java
direct-impl/src/test/java/com/microsoft/azure/cosmosdb/internal/directconnectivity/ReplicatedResourceClientPartitionSplitTest.java
direct-impl/src/test/java/com/microsoft/azure/cosmosdb/internal/directconnectivity/RntbdTransportClientTest.java
direct-impl/src/test/java/com/microsoft/azure/cosmosdb/internal/directconnectivity/StoreReaderDotNetTest.java
direct-impl/src/test/java/com/microsoft/azure/cosmosdb/internal/directconnectivity/StoreReaderTest.java
direct-impl/src/test/java/com/microsoft/azure/cosmosdb/internal/directconnectivity/TransportClientWrapper.java
gateway/src/main/java/com/microsoft/azure/cosmosdb/internal/BaseAuthorizationTokenProvider.java
sdk/src/test/java/com/microsoft/azure/cosmosdb/internal/directconnectivity/GatewayAddressCacheTest.java
sdk/src/test/java/com/microsoft/azure/cosmosdb/internal/directconnectivity/GatewayServiceConfigurationReaderTest.java

This is the cherry pick of this PR (https://github.com/Azure/azure-cosmosdb-java/pull/230 for 2.4.6 hotfix release) onto master.
description of the cherry picked PR: https://github.com/Azure/azure-cosmosdb-java/pull/230
This PR Includes the following memory improvements.
(The following numbers are based on running benchmark tool on 16cpu core Linux VM with ReadThroughput workload and 4000 as degree of concurrency.)
1) when reading from network wire (through netty ByteBuf) we used to copy data once to ByteArrayOutputStream and from that we created String. Later ByteArrayOutputStream will get garbage collected, on high load this can lead to GCing 20-30% unnecessary data. The improvement is to pool the buffers.
2) we were deserializing replica physicalAddress in the AddressSelector to URI …

memory improvements (cherry pick of #230 to master)

---

gateway/src/main/java/com/microsoft/azure/cosmosdb/rx/internal/query/DocumentQueryExecutionContextFactory.java
sdk/src/test/java/com/microsoft/azure/cosmosdb/rx/AggregateQueryTests.java

This PR fixes the issue of SDK throwing BadRequestException when maxItemCount is less than 0. 
https://github.com/Azure/azure-cosmosdb-java/issues/261

Removed BadRequestException when FeedOptions.maxItemCount is -1

---

README.md
benchmark/pom.xml
changelog/README.md
commons-test-utils/pom.xml
commons/pom.xml
commons/src/main/java/com/microsoft/azure/cosmosdb/internal/HttpConstants.java
commons/src/main/java/com/microsoft/azure/cosmosdb/internal/JavaStreamUtils.java
commons/src/main/java/com/microsoft/azure/cosmosdb/internal/routing/PartitionKeyRangeIdentity.java
direct-impl/pom.xml
direct-impl/src/main/java/com/microsoft/azure/cosmosdb/internal/directconnectivity/AddressResolver.java
direct-impl/src/main/java/com/microsoft/azure/cosmosdb/internal/directconnectivity/GatewayAddressCache.java
direct-impl/src/main/java/com/microsoft/azure/cosmosdb/internal/directconnectivity/GoneAndRetryWithRetryPolicy.java
direct-impl/src/main/java/com/microsoft/azure/cosmosdb/internal/directconnectivity/HttpTransportClient.java
examples/pom.xml
gateway/pom.xml
gateway/src/main/java/com/microsoft/azure/cosmosdb/rx/internal/ClientRetryPolicy.java
gateway/src/main/java/com/microsoft/azure/cosmosdb/rx/internal/caches/AsyncCache.java
pom.xml
sdk/pom.xml

This PR fixes a potential NPE issue and adds more logging.

null return fix and logging

---

commons/src/main/java/com/microsoft/azure/cosmosdb/internal/HttpConstants.java
direct-impl/src/main/java/com/microsoft/azure/cosmosdb/internal/directconnectivity/GatewayAddressCache.java
sdk/src/test/java/com/microsoft/azure/cosmosdb/internal/directconnectivity/GatewayAddressCacheTest.java

This PR will add x-ms-collectionroutingmap-refresh in header with value true in case of partition migration on backend , which will notify gateway to refresh collection routing map cache on address call

Adding collection routing map refresh flag on partition migration

---

benchmark/src/main/java/com/microsoft/azure/cosmosdb/benchmark/ReadMyWriteWorkflow.java
benchmark/src/test/java/com/microsoft/azure/cosmosdb/benchmark/ReadMyWritesConsistencyTest.java
commons/src/main/java/com/microsoft/azure/cosmosdb/rx/internal/Configs.java
commons/src/test/java/com/microsoft/azure/cosmosdb/rx/internal/ConfigsTests.java
direct-impl/pom.xml
direct-impl/src/main/java/com/microsoft/azure/cosmosdb/internal/directconnectivity/RntbdTransportClient.java
direct-impl/src/main/java/com/microsoft/azure/cosmosdb/internal/directconnectivity/rntbd/RntbdClientChannelHandler.java
direct-impl/src/main/java/com/microsoft/azure/cosmosdb/internal/directconnectivity/rntbd/RntbdClientChannelHealthChecker.java
direct-impl/src/main/java/com/microsoft/azure/cosmosdb/internal/directconnectivity/rntbd/RntbdClientChannelPool.java
direct-impl/src/main/java/com/microsoft/azure/cosmosdb/internal/directconnectivity/rntbd/RntbdEndpoint.java
direct-impl/src/main/java/com/microsoft/azure/cosmosdb/internal/directconnectivity/rntbd/RntbdObjectMapper.java
direct-impl/src/main/java/com/microsoft/azure/cosmosdb/internal/directconnectivity/rntbd/RntbdRequestTimer.java
direct-impl/src/main/java/com/microsoft/azure/cosmosdb/internal/directconnectivity/rntbd/RntbdServiceEndpoint.java
direct-impl/src/test/java/com/microsoft/azure/cosmosdb/internal/directconnectivity/RntbdTransportClientTest.java

See #298. Also: 
* Added the ability to set the Direct TCP protocol using:
- `-Dcosmos.directModeProtocol`\
the current mechanism
- `-Dazure.cosmos.directModeProtocl`\
for consistency with v4 and azure sdk guidelines
- `DIRECT_MODE_PROTOCOL` environment variable\
for consistency with other settings that we vary in CI test runs.

Add support for specifying default Direct TCP options using System properties

---

direct-impl/src/test/java/com/microsoft/azure/cosmosdb/internal/directconnectivity/GlobalEndPointManagerTest.java
gateway/src/main/java/com/microsoft/azure/cosmosdb/internal/routing/LocationCache.java
gateway/src/main/java/com/microsoft/azure/cosmosdb/rx/internal/ClientRetryPolicy.java
gateway/src/main/java/com/microsoft/azure/cosmosdb/rx/internal/GlobalEndpointManager.java
gateway/src/test/java/com/microsoft/azure/cosmosdb/internal/routing/LocationCacheTest.java
gateway/src/test/java/com/microsoft/azure/cosmosdb/rx/internal/ClientRetryPolicyTest.java
gateway/src/test/java/com/microsoft/azure/cosmosdb/rx/internal/RenameCollectionAwareClientRetryPolicyTest.java
sdk/src/main/java/com/microsoft/azure/cosmosdb/rx/internal/RxDocumentClientImpl.java
sdk/src/test/java/com/microsoft/azure/cosmosdb/rx/CollectionCrudTest.java

Porting PR from V3 https://github.com/Azure/azure-sdk-for-java/pull/6139

DR fixes for V2

---

gateway/src/main/java/com/microsoft/azure/cosmosdb/rx/internal/ClientRetryPolicy.java

* Fixed dont retry writes on forbidden
* Direct port of https://github.com/Azure/azure-sdk-for-java/pull/7243

Fixed dont retry writes on forbidden

---

gateway/src/main/java/com/microsoft/azure/cosmosdb/rx/internal/query/DocumentProducer.java
sdk/src/test/java/com/microsoft/azure/cosmosdb/internal/directconnectivity/GatewayAddressCacheTest.java

Doc producers are spun for each partition range, and each one should have its own copy of feedoptions. In the existing implementation same copy of feedoptions is being used for all the producers due to which there is a possibility of loosing continuation token depending on the order of creation of document producers when multiple (>2) partition ranges are present. This PR addresses this issue and ensures feedoptions are set properly for each producer.

Fixing a issue where feedoptions are getting overridden 

---

commons/pom.xml
commons/src/main/java/com/microsoft/azure/cosmosdb/BridgeInternal.java
commons/src/main/java/com/microsoft/azure/cosmosdb/DocumentClientException.java
commons/src/test/java/com/microsoft/azure/cosmosdb/DocumentClientExceptionTest.java
direct-impl/src/main/java/com/microsoft/azure/cosmosdb/internal/directconnectivity/rntbd/RntbdMetrics.java
direct-impl/src/main/java/com/microsoft/azure/cosmosdb/internal/directconnectivity/rntbd/RntbdRequestRecord.java
sdk/src/test/java/com/microsoft/azure/cosmosdb/rx/internal/ConsistencyTests2.java

This PR eliminates a `ConcurrentModificationException` that is thrown when the `DocumentClientException.requestHeaders` and `DocumentClientException.responseHeaders` are modified on one thread while they are being enumerated on another thread. This may happen, for example, when `DocumentClientException.toString` is called on one thread while `DocumentClientException.requestHeaders` or `DocumentClientException.responseHeaders`  are being updated on another.
This PR also:
-  tidies the DocumentClientException code,
- makes all modifiable DocumentClientException fields volatile, and
- adds a unit test to verify that no exceptions are thrown in the scenario this PR addresses.
See `DocumentClientExceptionTest.canEnumerateWhileUpdatingHeaders`.

DocumentClientException is now thread-safe

---

direct-impl/src/main/java/com/microsoft/azure/cosmosdb/internal/directconnectivity/rntbd/RntbdContext.java
direct-impl/src/main/java/com/microsoft/azure/cosmosdb/internal/directconnectivity/rntbd/RntbdContextDecoder.java
direct-impl/src/main/java/com/microsoft/azure/cosmosdb/internal/directconnectivity/rntbd/RntbdContextRequestEncoder.java
direct-impl/src/main/java/com/microsoft/azure/cosmosdb/internal/directconnectivity/rntbd/RntbdResponse.java
direct-impl/src/main/java/com/microsoft/azure/cosmosdb/internal/directconnectivity/rntbd/RntbdResponseDecoder.java
direct-impl/src/main/java/com/microsoft/azure/cosmosdb/internal/directconnectivity/rntbd/RntbdToken.java
direct-impl/src/main/java/com/microsoft/azure/cosmosdb/internal/directconnectivity/rntbd/RntbdTokenStream.java

```bash
mkdir azure-cosmos.results
git checkout master
profile=direct
mvn -P$profile -DargLine="-Dio.netty.leakDetectionLevel=paranoid -Dio.netty.leakDetection.targetRecords=255" verify | tee azure-cosmos.results/Verify-P$profile.output
```
A number of leaks detections that originate here:
- **com.microsoft.azure.cosmosdb.internal.directconnectivity.rntbd.RntbdResponse.lambda$release$0(RntbdResponse.java:221)**
- **com.microsoft.azure.cosmosdb.internal.directconnectivity.rntbd.RntbdTokenStream.releaseBuffers(RntbdTokenStream.java:125)**
Simplify reference counting implementation by changing the granularity of the instances of `RntbdResponse`, `RntbdToken`, and `RntbdTokenStream`. Specifically,
- Break a response `message` into three pieces as we do today: `frame`, `headers`, and …

Address memory leak in Direct TCP transport client

---

commons/src/main/java/com/microsoft/azure/cosmosdb/internal/ResourceId.java
gateway/src/main/java/com/microsoft/azure/cosmosdb/rx/internal/query/OrderByUtils.java
sdk/src/test/java/com/microsoft/azure/cosmosdb/rx/QueryValidationTests.java

This PR fixes an issue due to which the order by results when resuming from continuation token might contain duplicates/missing documents
- Adding a new method in ResourceId
- Adding a new test class to test the above scenario. This class can eventually be enhanced to add more tests around query validation.

Fixing an issue with order by query continuation token results

---

changelog/README.md

Please see this page: https://docs.microsoft.com/en-us/azure/cosmos-db/sql-api-sdk-async-java it has 2 titles. This PR is to remove the second title.

Removing H1 to reuse this content in a H2 for docs

---

README.md
benchmark/pom.xml
changelog/README.md
commons-test-utils/pom.xml
commons/pom.xml
commons/src/main/java/com/microsoft/azure/cosmosdb/internal/HttpConstants.java
direct-impl/pom.xml
examples/pom.xml
gateway/pom.xml
pom.xml
sdk/pom.xml

* Updated release version to 2.6.9
* Fixed duplicate results on order by when resuming from continuation token ([#341](https://github.com/Azure/azure-cosmosdb-java/pull/341))

Updated release version to 2.6.9

---

sdk/src/test/java/com/microsoft/azure/cosmosdb/rx/CollectionCrudTest.java

Sdk master branch test cases are failing as now BE service does not support lazy indexing.
Fixing the test case in this PR

Converting lazy index check to consistent index in test class

---

commons/src/main/java/com/microsoft/azure/cosmosdb/BridgeInternal.java
commons/src/main/java/com/microsoft/azure/cosmosdb/DocumentClientException.java
commons/src/main/java/com/microsoft/azure/cosmosdb/internal/HttpConstants.java
direct-impl/src/main/java/com/microsoft/azure/cosmosdb/internal/directconnectivity/GatewayAddressCache.java
gateway/src/main/java/com/microsoft/azure/cosmosdb/rx/internal/ClientRetryPolicy.java
gateway/src/main/java/com/microsoft/azure/cosmosdb/rx/internal/GlobalEndpointManager.java
gateway/src/main/java/com/microsoft/azure/cosmosdb/rx/internal/RxGatewayStoreModel.java
gateway/src/test/java/com/microsoft/azure/cosmosdb/rx/internal/ClientRetryPolicyTest.java
sdk/src/test/java/com/microsoft/azure/cosmosdb/rx/CollectionCrudTest.java
sdk/src/test/java/com/microsoft/azure/cosmosdb/rx/internal/NetworkFailureTest.java

Currently for tcp network exception we are doing region failover, which is causing problem for some users where due to some intermittent network issue on BE nodes sdk is sending traffic for next 5 min to other available region.
This PR will limit the region failover only in case of http network failure.

Fixing region fail over issue for direct tcp calls

---

commons/src/main/java/com/microsoft/azure/cosmosdb/ClientSideRequestStatistics.java
commons/src/main/java/com/microsoft/azure/cosmosdb/rx/internal/HttpClientFactory.java
commons/src/main/java/com/microsoft/azure/cosmosdb/rx/internal/RxDocumentServiceRequest.java
commons/src/test/java/com/microsoft/azure/cosmosdb/rx/internal/HttpClientFactoryTest.java
direct-impl/src/main/java/com/microsoft/azure/cosmosdb/internal/directconnectivity/GatewayAddressCache.java
sdk/src/test/java/com/microsoft/azure/cosmosdb/rx/internal/HttpRequestTimeoutTest.java
sdk/src/test/java/com/microsoft/azure/cosmosdb/rx/internal/directconnectivity/ClientSideRequestStatisticsTest.java

Currently we have an api on ConnectionPolicy setRequestTimeoutInMillis which sets the request time out for both TCP and HTTP requests.
We want to cap the lower value of http client request time out to 60 sec, as http network request call ends up into region fail over and also Gateway does not have any sla.
**Note:** This PR also contains the improvement on AddressResolutionStatistics in ClientSideRequestStatistics, which include error message if there is any failure on address cache refresh call, also including flag inflightRequest which will indicate whether address call finished in lifetime of the the request.
**Also closes query plan issue**
closes https://github.com/Azure/azure-cosmosdb-java/issues/359

Improving http request time out avoiding region failover for high latency request

---

README.md
changelog/README.md

Added change notes for 2.6.11 release we did in September

Update README.md for 2.6.11 release

---

CODEOWNERS
direct-impl/src/test/java/com/microsoft/azure/cosmosdb/internal/directconnectivity/WebExceptionUtilityTest.java
gateway/src/main/java/com/microsoft/azure/cosmosdb/internal/directconnectivity/WebExceptionUtility.java

* Removed generic IO exception condition in network failure. Replaced with specific exceptions. Included in unit testing.
* This is a direct port of PR - https://github.com/Azure/azure-sdk-for-java/pull/16469

Removed generic IO exception condition in network failure. Replaced with specific exceptions. Included in unit testing

---

README.md
benchmark/pom.xml
changelog/README.md
commons-test-utils/pom.xml
commons/pom.xml
commons/src/main/java/com/microsoft/azure/cosmosdb/internal/HttpConstants.java
direct-impl/pom.xml
examples/pom.xml
gateway/pom.xml
pom.xml
sdk/pom.xml

* Release version update for 2.6.13

Release version update for 2.6.13

---

commons/src/main/java/com/microsoft/azure/cosmosdb/ConnectionPolicy.java

Current texts imply that write requests will "only" be directed to the first preferred location.

Clarify ConnectionPolicy multi write region configs

---

gateway/src/main/java/com/microsoft/azure/cosmosdb/rx/internal/query/TopDocumentQueryExecutionContext.java
sdk/src/test/java/com/microsoft/azure/cosmosdb/rx/TopQueryTests.java

1. The issue is happening when using the top query to get the top of 'x'  items where 'x' is greater than the total number of items in the database.
2. Link for the ICM - https://portal.microsofticm.com/imp/v3/incidents/details/286671765/home

Fixing the response header 'x-ms-continuation' value issue.
